---
- name: Launch a Google Compute Engine instance from localhost
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - gce_instance

- name: Provision the GCE instance with Docker
  hosts: biostarhosts
  gather_facts: False
  user: root
  sudo: yes

  roles:
    - docker

- include: biostar.yml
