---
- name: Add docker apt key
  apt_key:
    url: https://get.docker.io/gpg
    state: present
  sudo: True

- name: Add docker apt repo
  shell: echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
  sudo: True

- name: Install Docker
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - lxc-docker
    - python-pip
  sudo: True

- name: Install docker-py
  pip:
    name: docker-py
  sudo: True

- name: Add user ubuntu to the docker group 
  user:
    name: ubuntu
    groups: docker,
    append: yes
  sudo: True

- name: Create host SSH private key
  command: ssh-keygen -t rsa -N "" -f /home/ubuntu/.ssh/id_rsa
    creates=/home/ubuntu/.ssh/id_rsa

- name: Read SSH public key
  command: cat /home/ubuntu/.ssh/id_rsa.pub
  register: host_ssh_public_key

- name: Create working dirs
  shell: mkdir {{ host_dir_for_codebase }} && mkdir {{ host_dir_for_dockerfiles }} && mkdir {{ host_dir_for_dockervolumes }}
  sudo: True

- name: Set permissions on working dirs
  shell: chown ubuntu:ubuntu {{ host_dir_for_codebase }} && chown ubuntu:ubuntu {{ host_dir_for_dockerfiles }} && chown ubuntu:ubuntu {{ host_dir_for_dockervolumes }}
  sudo: True